#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
bitcoin_parser
@author: ethanweber
"""


import urllib3
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import os
import pprint
import re


#driver = webdriver.Chrome('/Users/ethanweber/Downloads/chromedriver') 

bitcoin_file = 'bitcoin_data.htm'
ethereum_file = 'ethereum_data.htm'
ripple_file = 'ripple_data.htm'
test = "steemit_test.htm"

ethereum = BeautifulSoup(open(ethereum_file), "html.parser")

def parse_for_author(html_thing, number):
    try:
        return html_thing.find_all(attrs="author")[number].a['href'].split("/@",1)[1]
    except:
        return "escape"

def get_authors(soup):
    author_list = []
    author_no = 0
    author = ""
    while author != 'escape':
        author = parse_for_author(soup, author_no)
        author_no += 1
        author_list.append(author)
    return author_list

ethereum_authors = get_authors(ethereum)
df = pd.DataFrame()
df['coin'] = 'ethereum'
df['author'] = pd.Series(ethereum_authors)
df.to_csv('ethereum.csv')